services:

  mysql:
    image: mysql:8
    container_name: gran_poeta_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: gran_poeta
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gran_poeta_net

  backend:
    build: ./backend
    container_name: gran_poeta_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: user123
      DB_NAME: gran_poeta
      JWT_SECRET: clave_super_secreta_cambiar_en_produccion
      JWT_EXPIRES: 8h
    depends_on:
      - mysql
    networks:
      - gran_poeta_net

  frontend:
    image: nginx:alpine
    container_name: gran_poeta_frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend/static:/usr/share/nginx/html
    networks:
      - gran_poeta_net

volumes:
  db_data:

networks:
  gran_poeta_net:
    driver: bridge